client:
  known_hosts:
    mimir:
      ip: '192.168.0.13'
      port: 5002
    desktop:
      ip: '192.168.0.204'
      port: 5001
    localhost:
      ip: '127.0.0.1'
      port: 5001

server:
  separator: "<SEPARATOR>"
  buffer_size: 4096
  server_host: '0.0.0.0'
  server_port: 5002

