known-hosts:
  public:
    ip: '24.254.180.168'
    port: 5002
  mimir:
    ip: '192.168.0.13'
    port: 5002
  desktop:
    ip: '192.168.0.204'
    port: 5001
  localhost:
    ip: '127.0.0.1'
    port: 5001

settings:
  separator:
  buffer_size: 4096
  host: '0.0.0.0'
  port: 5002
  dest_dir: 'received_files'
  archive:  'xfer.tar.gz'
