client:
  known_hosts:
    logank:
      ip: ''
      port: 5002
    desktop:
      ip: ''
      port:
    localhost:
      ip: ''
      port:
  archive_name: "xfer.tar.gz"
server:
  separator: "<SEPARATOR>"
  buffer_size: 4096
  server_host: '0.0.0.0'
  server_port: 5002
  destination_dir: "received_files"